name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: TheClusterFlux/central-workflows/.github/workflows/deploy.yaml@main
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      kubernetes-context: ${{ secrets.KUBERNETES_CONTEXT }}
      