name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: TheClusterFlux/central-workflows/.github/workflows/deploy.yaml@main
    with:
      dockerhub-username: ${{ github.secret_source.DOCKER_USERNAME }}
      dockerhub-password: ${{ github.secret_source.DOCKER_PASSWORD }}
      kubernetes-context: ${{ github.secret_source.KUBERNETES_CONTEXT }}
      

